### ISSUE TITLE
Tests & Application fail with AnormException: ColumnName(COMPUTER.NAME,Some(NAME))]

### ISSUE THREAD

**Issue by hakanernam** [playframework/play-anorm#10]
Cloning the repo and running either `activator test` (or `activator new`) results in AnormException:

```
[info] Compiling 3 Scala sources to /Users/hakan/Workspaces/Learning/Play/play-anorm/target/scala-2.11/test-classes...
[info] application - Creating Pool for datasource 'default'
[info] c.z.h.HikariDataSource - HikariPool-0 - is starting.
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[info] ModelSpec:
[info] Computer model
[info] - should be retrieved by id
[info] - should be listed along its companies
[info] - should be updated if needed
[info] application - Shutting down connection pool.
[info] c.z.h.p.HikariPool - HikariPool-0 - is closing down.
[info] IntegrationSpec:
[info] Application
[info] application - Creating Pool for datasource 'default'
[info] c.z.h.HikariDataSource - HikariPool-1 - is starting.
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[error] application -

! @70490j46c - Internal server error, for (GET) [/computers] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[AnormException: ColumnName(COMPUTER.NAME,Some(NAME))]]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
    at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
    at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
    at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
    at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
    at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
Caused by: anorm.AnormException: ColumnName(COMPUTER.NAME,Some(NAME))
[info] application - Shutting down connection pool.
[info] c.z.h.p.HikariPool - HikariPool-1 - is closing down.
[info] - should work from within a browser *** FAILED ***
[info]   org.openqa.selenium.NoSuchElementException: Element not found
[info] For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
[info] Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
[info] System info: host: 'HMBP.local', ip: '192.168.1.50', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_77'
[info] Driver info: driver.version: unknown
[info]   at org.fluentlenium.core.domain.FluentListImpl.first(FluentListImpl.java:27)
[info]   at IntegrationSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(IntegrationSpec.scala:16)
[info]   at IntegrationSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(IntegrationSpec.scala:13)
[info]   at play.api.test.PlayRunners$class.running(Helpers.scala:99)
[info]   at play.api.test.Helpers$.running(Helpers.scala:382)
[info]   at play.api.test.PlayRunners$class.running(Helpers.scala:87)
[info]   at play.api.test.Helpers$.running(Helpers.scala:382)
[info]   at IntegrationSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(IntegrationSpec.scala:13)
[info]   at IntegrationSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(IntegrationSpec.scala:13)
[info]   at IntegrationSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(IntegrationSpec.scala:13)
[info]   ...
[info] FunctionalSpec:
[info] application - Creating Pool for datasource 'default'
[info] c.z.h.HikariDataSource - HikariPool-2 - is starting.
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[info] HomeController
[info] - should redirect to the computer list on /
[info] - should list computers on the the first page *** FAILED ***
[info]   anorm.AnormException: ColumnName(COMPUTER.NAME,Some(NAME))
[info]   ...
[info] - should filter computer by name
[info] - should create new computer
[info] application - Shutting down connection pool.
[info] c.z.h.p.HikariPool - HikariPool-2 - is closing down.
[info] ScalaTest
[info] Run completed in 11 seconds, 896 milliseconds.
[info] Total number of tests run: 8
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 6, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
[error] Failed: Total 8, Failed 2, Errors 0, Passed 6
[error] Failed tests:
[error]     IntegrationSpec
[error]     FunctionalSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 26 s, completed May 13, 2016 12:39:45 PM
```

**Comment by itamarro** [comment]
Hey @hakanernam, you're right about the issue.

For now, if you change the anorm version to 2.5.0 (in build.sbt) it should work fine, see this pull request for more details: https://github.com/playframework/play-anorm/pull/11

**Comment by Sergey80** [comment]
2.5.2 seems same issue.

**Comment by Sergey80** [comment]
and same in 3.0.0-M1

**Comment by cchantep** [comment]
@Sergey80 3.0.0-M1 is a "wrong" artifact. The latest one is 2.5.2, from July. The issue has been fixed after, and is waiting for the next publish https://github.com/playframework/anorm/pull/140
